version: '3.4'
networks:
  cards:
    driver: bridge
services:
  cards-web-api:
    image: docker.io/library/cardswebapi
    depends_on:
      cards-web-api-db: 
        condition: service_started
    container_name: cardswebapi
    ports:
      - "5000:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=cards-web-api-db;Port=5432;Username=apiuser;Password=apiuser;Database=CardsDb;
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - cards
  cards-web-api-db:
    image: postgres:latest
    container_name: cards-web-api-db
    environment:
      POSTGRES_USER: "apiuser"
      POSTGRES_PASSWORD: "apiuser"
      POSTGRES_DB: "CardsDb"
    ports:
      - "5435:5432"
    expose:
      - "5435"      
    restart: always
    volumes:
      - cards_web_api_data:/var/lib/postgresql/data      
    networks:
      - cards
volumes:
  cards_web_api_data: